### PR TITLE
1.20.1

### PR DESCRIPTION
**Pull request by MrGII**

### CODE REVIEW

**Comment by Pomi108** [comment]
What are the model files for?

**Comment by MrGII** [comment]
They are needed to make the side textures different from the top/bottome textures

**Comment by Pomi108** [comment]
Why though? Does the original mod do that?

**Comment by MrGII** [comment]
The original mod does not do this, I did this so the ores core correctly represents how an ore of that type would have looked as a Minecraft ore. If this is considered an unfaithful change to the textures, I will upload to the repository a version without the top and bottom changes from now on and you can reject the request as there is no other change.

**Comment by Pomi108** [comment]
Yeah this repository is only for upscaling the original mod textures, not any additional changes. What you've made can be uploaded as an add-on to the site

**Comment by 3vorp** [comment]
I'm pretty sure that accurate gilded blackstone is already an addon on the site lol, maybe contact the author for more information on maybe adding that to the same post or something idk

**Pull request closed without merging**
