### PR TITLE
raised has it own hotbar selection in its assets for 1.20.2+

### PR DESCRIPTION
**Pull request by minimiscus**
yes i recreated my fork 3 times just so I could get rid of the other commits

### CODE REVIEW

**Comment by 3vorp** [comment]
you know you can just squash commits right

**Comment by minimiscus** [comment]
uh uhhh lets just say there were other issues definitely because I don't know how to use git terminal

**Comment by 3vorp** [comment]
https://desktop.github.com

**Comment by minimiscus** [comment]
errr i see no option for squashing commits

**Comment by 3vorp** [comment]
you can only squash something that's not committed or not merged yet, git really hates when you delete history — you can amend an existing commit though which does some weird stuff behind the scenes (can cause issues with deployments) but works for simple storage like this

**Pull request merged**
