### PR TITLE
1.20.1

### PR DESCRIPTION
**Pull request by phuccom000**

### CODE REVIEW

**Comment by minimiscus** [comment]
You shouldn’t really have deleted any of the text files

**Comment by phuccom000** [comment]
should i have kept the README since it's from the main branch instead of 1.20.1
the license.txt i restored it already after accidentally delete it

**Comment by minimiscus** [comment]
README can be deleted

**Comment by phuccom000** [comment]
then will this pull request be accepted or is there any other problem?

**Pull request closed without merging**
